env:
  browser: true
  es2021: true

extends:
  - xo

parserOptions:
  ecmaVersion: 13
  sourceType: module

globals:
  tickets: readonly
  action: readonly
  cryptr: readonly
  config: readonly
  utils: readonly
  log: readonly
  db: readonly

rules:
  no-negated-condition: off
  capitalized-comments: off
  no-case-declarations: off
  no-warning-comments: off
  operator-linebreak: off
  no-useless-return: off
  no-await-in-loop: off
  comma-dangle: off
  default-case: off
  dot-notation: off
  brace-style: off
  complexity: off
  camelcase: off
  no-empty: off
  no-eval: off
  radix: off
  curly: off

  quotes:
    - error
    - double

  object-curly-spacing:
    - error
    - always
